# Develop phpvirtualbox in docker

# ufw allow proto tcp from 172.17.0.0/24 to 172.17.0.1 port 18083 comment 'vboxweb'

phpvbox:
  build: .
  restart: always
  ports:
    - 18888:80
  volumes:
    - .:/var/www/html

phpvbox_monitoring:
  image: nginx:alpine
  restart: always
  ports:
    - 18889:80
